name: CD to GitHub Packages

on:
  push:
    branches: [ main ] 
permissions:
  packages: write  # Ключевое право!
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew 

      
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}  # Использование секрета
        run: ./gradlew publish

