name: CD Main
on:
  workflow_run:
    workflows: ["CIMain"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew 
  
      - name: Publish to GitHub Packages 
        run: | 
          ./gradlew publish 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_USER: ${{ github.actor }}
