name: CI for Dev on Push

on:
  push:
    branches: [dev]

jobs:
  build-test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Fast build and test
        run: ./gradlew build test --continuous
